### ISSUE TITLE
Governance to org-docs

### ISSUE THREAD

**Issue by oesteban** [nipreps/GOVERNANCE#7]

**Comment by effigies** [comment]
Would suggest *all docs* (even per-project like list of current/former contributors) are maintained here.

**Comment by oesteban** [comment]
something like having one folder per project under which you find the structure replicated (and customized) for the project?

The only issue I can see with that is for the CONTRIBUTORS.md and the ROADMAP.md files, probably. The reason is that you probably want to ask people to write their names themselves in the list as the maintainers of the project may not be able to accept the PR and removes independence from them in the project.

For the others, it would be totally okay, I believe.

**Comment by effigies** [comment]
Ah, maybe contributors makes sense to have local to the project, now that you put it that way.
